Repository astral-sh/ruff-vscode, pull requests merged in 2024-07, with the labels that each got.

#516 Validate Python interpreter version for native server
  src/extension.ts
Labels: bug

#539 Use `spawn` rather than `exec` to support paths with spaces
  src/common/server.ts
Labels: bug

#544 Use `execFile` rather than `spawn`
  src/common/server.ts
Labels: internal

#545 Fix typo in ruff.configurationPreference markdownDescription
  package.json
Labels: documentation

#547 Guide to opt-in to Notebook support in native server
  README.md
Labels: documentation

#564 Remove reference to non-existent [1]
  README.md
Labels: documentation
