Repository astral-sh/ruff-vscode, pull requests merged in 2024-08, with the labels that each got.

#572 Support `red_knot` binary for server
  src/common/server.ts
Labels: internal

#584 Fix ruff discovery for paths containing symbols that can't be represented by the local encoding
  bundled/tool/find_ruff_binary_path.py
  package.json
  pyproject.toml
  src/common/constants.ts
Labels: bug

#591 Update README section for notebook support for Ruff 0.6
  README.md
Labels: documentation
